// <auto-generated />
using Jamrah.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jamrah.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Jamrah.Backend.Entities.Goal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("endDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentGoalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parentGoalId");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("startDate");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tagId");

                    b.HasKey("Id");

                    b.HasIndex("ParentGoalId");

                    b.HasIndex("TagId");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.GoalProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("FocusMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("focusMinutes");

                    b.Property<string>("GoalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goalId");

                    b.Property<double>("ProgressValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("progressValue");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("GoalId");

                    b.ToTable("goal_progress", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Habit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#3b82f6")
                        .HasColumnName("color");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DurationEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("durationEnd");

                    b.Property<string>("DurationStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("durationStart");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("yearly")
                        .HasColumnName("durationType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.HabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("HabitId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("habitId");

                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("HabitId");

                    b.HasIndex("HabitId", "Date")
                        .IsUnique();

                    b.ToTable("habit_logs", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("createdAt");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endTime");

                    b.Property<double>("FocusMinutes")
                        .HasColumnType("REAL")
                        .HasColumnName("focusMinutes");

                    b.Property<string>("GoalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("goalId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("note");

                    b.Property<double>("PlannedMinutes")
                        .HasColumnType("REAL")
                        .HasColumnName("plannedMinutes");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("startTime");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tagId");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("taskId");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("taskName");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("TagId");

                    b.HasIndex("TaskId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.TaskItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("completed");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("GoalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("goalId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parentTaskId");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Goal", b =>
                {
                    b.HasOne("Jamrah.Backend.Entities.Goal", "ParentGoal")
                        .WithMany("Children")
                        .HasForeignKey("ParentGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jamrah.Backend.Entities.Tag", "Tag")
                        .WithMany("Goals")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentGoal");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.GoalProgress", b =>
                {
                    b.HasOne("Jamrah.Backend.Entities.Goal", "Goal")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.HabitLog", b =>
                {
                    b.HasOne("Jamrah.Backend.Entities.Habit", "Habit")
                        .WithMany("Logs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Session", b =>
                {
                    b.HasOne("Jamrah.Backend.Entities.Goal", "Goal")
                        .WithMany("Sessions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jamrah.Backend.Entities.Tag", "Tag")
                        .WithMany("Sessions")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Goal");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.TaskItem", b =>
                {
                    b.HasOne("Jamrah.Backend.Entities.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jamrah.Backend.Entities.TaskItem", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Goal");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Goal", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProgressRecords");

                    b.Navigation("Sessions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Habit", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.Tag", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Jamrah.Backend.Entities.TaskItem", b =>
                {
                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
